name: Run tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php:
          - 8.2
          - 8.1
          - 8.0
          - 7.4
          - 7.3
          - 7.2
        laravel:
          - 9
          - 8
          - 7
          - 6

    name: PHP:${{ matrix.php }} - Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}.*" --no-interaction --no-update --dev
          composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

      - name: Run Tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist

      # Exclude specific PHP versions for certain Laravel versions
      - name: Check excluded versions
        if: |
          matrix.php == '7.2' && matrix.laravel == '9' ||
          matrix.php == '7.3' && matrix.laravel == '9' ||
          matrix.php == '7.4' && matrix.laravel == '9' ||
          matrix.php == '7.2' && matrix.laravel == '8' ||
          matrix.php == '8.1' && matrix.laravel == '7' ||
          matrix.php == '8.2' && matrix.laravel == '7' ||
          matrix.php == '8.1' && matrix.laravel == '6' ||
          matrix.php == '8.2' && matrix.laravel == '6'
        continue-on-error: true
        run: PHP:${{ matrix.php }} - Laravel:${{ matrix.laravel }}"
